language: python
python:
  - "2.7"
env:
  - DJANGO=1.11.21
install:
  - pip install -r dev/requirements.txt
script:
  - pep8 --exclude=IPy.py --ignore=E501 vrtManager accounts computes \
                                        console create instances interfaces \
                                        networks secrets storages
  - pyflakes vrtManager accounts computes console create instances interfaces \
             networks secrets storages
  - python manage.py migrate
  - python manage.py test --settings=webvirtcloud.settings-dev
